[package]
name = "dux-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.204", features= ["derive"]}
config = "0.14.0"
clap = { version = "4.5.9", features = ["derive"] }
duxcore = "0.1.2"
